### ISSUE TITLE
Stone Quarry v 3.1.5 prevents me from joining a mutiplayer

### ISSUE THREAD

**Issue by DracomancerWill** [DArkHekRoMaNT/StoneQuarry#18] opened 2023-10-06 11:34 UTC
### Mod Version

3.1.5

### CommonLib Version

2.2.0

### Game Version

1.18.12 (Stable)

### OS

Windows

### Play mode

Multiplayer

### Problem

when logging ion a multiplayer world, my game crashes and displays a nessage saying the following: "Don't know how to instantiate item of class 'ItemRubbleHammer' did you forget to register a mapping?"

The crash error log is attached below.

### Logs

```bash
Running on 64 bit Windows with 32651 MB RAM
Game Version: v1.18.12 (Stable)
06/10/2023 08:18:51: Critical error occurred
Loaded Mods: degrees1499@1.0.0, aculinaryartillery@1.0.15, backpackpack@1.0.3, betterruins@0.2.2, butcheringfix@1.0.0, cavecontent@1.0.1, Ceramos@0.4.1, chiseltools@1.8.4, craftingtable@0.4.0, cralutweaks@1.0.2, creaturescan@1.0.0, HangingOilLamps@1.0.1, hideandfabric@1.3.0, juicyores@1.0.0, knappingmastery@1.0.1, lanternliner@0.1.0, mannequinstand@1.0.1, millwright@1.0.9, moreclasses@1.2.5, MoreTorchHolders@1.0.0, MoveLikeKaji@0.0.3, nailsmold@1.0.1, OresAPlenty@3.1.0, palisademod@1.1.0, primitivesurvival@3.2.8, roas@1.0.0, rooffix@0.0.1, sca@1.0.1, spyglass@0.4.5, translocatorengineeringredux@1.4.7, game@1.18.12, wildcraft@1.6.6, abcsreborn@0.1.2, alchemy@1.6.16, alloycalculator@1.0.0, ancienttools@1.5.9, animalcages@2.2.0, autoatlas@1.0.1, betterfirepit@1.1.1, blocksoverlay@2.2.1, carryon@1.6.0, commonlib@2.2.0, composter@1.1.0, cooperativecombat@1.1.1, darkerdrifterspawns@1.0.1, expandedfoods@1.6.7, farmlanddropssoil@1.4.0, fromgoldencombs@1.4.21, medievalexpansion@3.11.1, medievalmap@1.4.1, moreanimals@1.2.4, moreclassesshieldfix@0.0.2, nemi@1.1.0, petai@1.8.1, primitivetools@1.4.1, prospectorinfo@4.3.0, prospecttogether@1.2.4, sharablewaypoints@1.3.2, simplestep@1.0.8, statushud@1.4.3, stepup@1.2.0, stillnecessaries@1.0.1, stonebakeoven@1.1.0, tablet@0.1.4, mirrors@1.7.2, th3dungeon@0.2.0, usefulstuff17@1.2.0, creative@1.18.12, vsquest@0.5.0, survival@1.18.12, vsvillage@0.7.3, wildfarmingrevival@1.1.6, xlib@0.7.4, metalrecovery@0.1.19-pre.1, betterstepping@1.0.0, cats@1.8.0, dowsedinsalt@1.0.0, em@2.4.1, feverstonewilds@1.4.3, maltiezfirearms@0.1.11, playercorpse@1.8.0, wolftaming@1.8.0, xskills@0.7.5, bricklayers@2.4.0, wildcraftxskillspatch@0.2.0, xskillscatchablepatch@1.0.0
System.Exception: Don't know how to instantiate item of class 'ItemRubbleHammer' did you forget to register a mapping?
   at Vintagestory.Common.ClassRegistry.CreateItem(String itemClass) in VintagestoryLib\Common\ClassRegistry.cs:line 273
   at Vintagestory.Common.ItemTypeNet.ReadItemTypePacket(Packet_ItemType packet, IWorldAccessor world, ClassRegistry registry) in VintagestoryLib\Common\Network\ItemTypeNet.cs:line 192
   at Vintagestory.Client.NoObf.ClientSystemStartup.PopulateItems(List`1 items, Int32 listSize) in VintagestoryLib\Client\Systems\Startup.cs:line 563
   at Vintagestory.Client.NoObf.ClientSystemStartup.LoadItemTypes() in VintagestoryLib\Client\Systems\Startup.cs:line 392
   at Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerAssets_Step1() in VintagestoryLib\Client\Systems\Startup.cs:line 334
   at Vintagestory.API.Common.TyronThreadPool.<>c__DisplayClass12_0.<QueueTask>b__0(Object a) in VintagestoryApi\Common\TyronThreadPool.cs:line 108
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

**Comment by DArkHekRoMaNT** [comment] 2023-10-06 11:54
What's in client-main.txt? There must be an actual error there

**Comment by DArkHekRoMaNT** [comment] 2023-10-22 14:48
Is this still relevant?

**Comment by DArkHekRoMaNT** [comment] 2023-10-22 14:59
I think this is a duplicate of #17 , see solution there.

**Closed by DArkHekRoMaNT** 2023-10-22 14:59 UTC
Labels: bug
